NeuroContact/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app_main.urls")),
    path("users/", include("users.urls")),
    path("app_predict/", include("app_predict.urls")),
    path("app_contacts/", include("app_contacts.urls")),
    path("app_notes/", include("app_notes.urls")),
    path("app_files/", include("app_files.urls")),
    path("app_news/", include("app_news.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_notes/urls.py
from django.urls import path, include

from . import views

app_name = "app_notes"

urlpatterns = [
    path("", views.main, name="notes"),
    path("tag/", views.tag, name="tag"),
    path("note/", views.note, name="note"),
    path("detail/<int:note_id>", views.detail, name="detail"),
    path("done/<int:note_id>", views.set_done, name="set_done"),
    path("delete/<int:note_id>", views.delete_note, name="delete"),
    path('edit/<int:note_id>', views.edit_note, name='edit_note'),
    path('search/', views.search, name='search'),
    path('sort/', views.sort, name='sort'),
]

users/urls.py
from django.urls import path, include
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

from . import views
from .forms import LoginForm

app_name = "users"

urlpatterns = [
    path(
        "signup/",
        views.RegisterView.as_view(),
        name="signup",
    ),
    path(
        "signin/",
        LoginView.as_view(template_name="users/signin.html", form_class=LoginForm),
        name="signin",
    ),
    path(
        "signout/",
        LogoutView.as_view(template_name="users/signout.html"),
        name="signout",
    ),
    path("reset-password/", views.ResetPasswordView.as_view(), name="password_reset"),
    path(
        "reset-password/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset-password/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url="/users/reset-password/complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset-password/complete/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

app_notes/models.py
from django.db import models

from django.contrib.auth.models import User

"""
Basic models for notes and tags
"""


class Tag(models.Model):
    name = models.CharField(max_length=20, null=False, unique=True)

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    objects = models.Manager()

    def __str__(self):
        return self.name


class Note(models.Model):
    title = models.CharField(max_length=20)
    body = models.TextField()
    date = models.DateField(null=True, blank=True)
    is_done = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    tag = models.ManyToManyField(Tag)
    objects = models.Manager()

    def __str__(self):
        return self.title

app_notes/forms.py
from django.forms import ModelForm, CharField, TextInput
from .models import Tag, Note


class TagForm(ModelForm):
    name = CharField(min_length=3, max_length=25, required=True, widget=TextInput())

    class Meta:
        model = Tag
        fields = ["name"]


class NoteForm(ModelForm):
    title = CharField(min_length=5, max_length=50, required=True, widget=TextInput())
    body = CharField(
        min_length=10, max_length=150, required=True, widget=TextInput()
    )

    class Meta:
        model = Note
        fields = ["title", "body"]
        exclude = ["tag"]

app_notes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .forms import TagForm, NoteForm
from .models import Tag, Note


@login_required
def main(request):
    notes = (
        Note.objects.filter(user=request.user).all()
        if request.user.is_authenticated
        else []
    )
    tags = (
        Tag.objects.filter(user=request.user).all()
        if request.user.is_authenticated
        else []
    )
    return render(request, "app_notes/notes.html", {"notes": notes, "tags": tags})


@login_required
def tag(request):
    if request.method == "POST":
        form = TagForm(request.POST)
        if form.is_valid():
            tag = form.save(commit=False)
            tag.user = request.user
            tag.save()
            return redirect(to="app_notes:tag")
        else:
            return render(request, "app_notes/tag.html", {"form": form})

    return render(request, "app_notes/tag.html", {"form": TagForm()})


@login_required
def note(request):
    tags = Tag.objects.filter(user=request.user).all()

    if request.method == "POST":
        form = NoteForm(request.POST)
        if form.is_valid():
            new_note = form.save(commit=False)
            new_note.user = request.user
            new_note.save()
            choice_tags = Tag.objects.filter(
                name__in=request.POST.getlist("tags"), user=request.user
            )
            for tag_ in choice_tags.iterator():
                new_note.tag.add(tag_)

            return redirect(to="app_notes:notes")
        else:
            return render(request, "app_notes/note.html", {"tags": tags, "form": form})

    return render(request, "app_notes/note.html", {"tags": tags, "form": NoteForm()})


@login_required
def detail(request, note_id):
    note = get_object_or_404(Note, pk=note_id, user=request.user)
    return render(request, "app_notes/detail.html", {"note": note})


@login_required
def set_done(request, note_id):
    Note.objects.filter(pk=note_id, user=request.user).update(is_done=True)
    return redirect(to="app_notes:notes")


@login_required
def delete_note(request, note_id):
    Note.objects.get(pk=note_id, user=request.user).delete()
    return redirect(to="app_notes:notes")


@login_required
def search(request):
    if "query" in request.GET:
        query = request.GET["query"]
        notes = Note.objects.filter(
            Q(title__icontains=query) | Q(body__icontains=query), user=request.user
        )
        # search_notes = pagination(request, notes)
        return render(request, "app_notes/search_results.html", {"notes": notes})
    else:
        return redirect(to="app_notes:notes")


@login_required
def edit_note(request, note_id):
    note = get_object_or_404(Note, pk=note_id, user=request.user)
    tags = Tag.objects.filter(user=request.user).all()

    if request.method == "POST":
        form = NoteForm(request.POST, instance=note)
        if form.is_valid():
            edited_note = form.save(commit=False)
            edited_note.user = request.user
            edited_note.save()
            edited_note.tag.clear()
            choice_tags = Tag.objects.filter(
                name__in=request.POST.getlist("tags"), user=request.user
            )
            for tag_ in choice_tags.iterator():
                edited_note.tag.add(tag_)

            return redirect(to="app_notes:notes")
        else:
            return render(
                request,
                "app_notes/edit_note.html",
                {
                    "note": note,
                    "tags": tags,
                    "form": form,
                },
            )

    form = NoteForm(instance=note)
    return render(
        request,
        "app_notes/edit_note.html",
        {
            "note": note,
            "tags": tags,
            "form": form,
        },
    )


@login_required
def sort(request):
    if request.method == "GET":
        selected_tags = request.GET.getlist("selected_tags")
        notes = Note.objects.filter(
            tag__name__in=selected_tags, user=request.user
        ).distinct()
        return render(
            request,
            "app_notes/search_results.html",
            {"notes": notes, "selected_tags": selected_tags},
        )
    else:
        return redirect(to="app_notes:notes")

app_notes/templates/app_notes/detail.html
{% extends 'app_main/base.html' %}

{% block notes %}
{% load extract_tags %}
{% load static %}

<section id="five" class="wrapper style1 fade-up">
    <div class="inner">
        <h2>Note Details</h2>

        <a href="/app_notes" class="button small">to the list of notes</a>
        <p></p>

        <h3>{{ note.title }}</h3>
        <div class="row">
            <div class="col-6 col-12-medium">
                <ul class="alt">
                    <li>Description: <b>{{ note.body }}</b></li>
                    <li>Time of creation: <i>{{ note.created_at|date:"y-m-d h:i A" }}</i></li>
                    {% if note.is_done %}
                    <li>Status: Completed</li>
                    {% else %}
                    <li>Status: <i>Not implemented</i></li>
                    {% endif %}
                    <li>Tags: <small>{{ note.tag|tag_filter }}</small></li>
                </ul>
            </div>
        </div>

    </div>
</section>

{% endblock %}

app_notes/templates/app_notes/edit_note.html
{% extends 'app_main/base.html' %}

{% block notes %}
{% if user.is_authenticated %}

<section id="five" class="wrapper style1 fade-up">
    <div class="inner">
        <h2>Edit a Note</h2>

        <div class="form-box shadow-lg bg-body-tertiary rounded-5">
            <form method="POST" action="{% url 'app_notes:edit_note' note_id=note.id %}">
                {% csrf_token %}
                <div class="form-group">
                    <label>Name:</label>
                    {{ form.title }}
                    <span>{{ form.errors.title }}</span>
                </div>
                <div class="form-group">
                    <label>Description:</label>
                    {{ form.body }}
                    <span>{{ form.errors.body }}</span>
                </div>
                <div class="form-group">
                    <label> Select Tags:
                        <select name="tags" multiple="multiple" required>
                            {% for tag in tags %}
                            <option value="{{tag.name}}">{{tag.name}}</option>
                            {% endfor %}
                        </select>
                    </label>
                </div>
                <button type="submit" class="btn btn-primary">Save</button>
            </form>
        </div>
        {% else %}
        <div style="text-align: center;">
            <h2>Sign up or login to your account!</h2>
        </div>
        {% endif %}

    </div>
</section>

{% endblock %}

app_notes/templates/app_notes/note.html
{% extends 'app_main/base.html' %}

{% block notes %}
{% load static %}

<section id="five" class="wrapper style1 fade-up">
    <div class="inner">
        <h2>Add a note</h2>

        <a href="/app_notes" class="button small">to the list of notes</a>

        <div class="form-block">
            <br>
            <form method="POST" action="{% url 'app_notes:note' %}">
                {% csrf_token %}
                <div class="row gtr-uniform">
                    <div class="col-6">
                        <label> Name:
                            {{ form.title }}
                        </label>
                    </div>
                    <span>{{ form.errors.title }}</span>

                    <div class="col-6">
                        <label> Description:
                            {{ form.body }}
                        </label>
                    </div>
                    <span>{{ form.errors.body }}</span>

                    <div class="col-6">
                        <label> Select Tags:
                            <select name="tags" multiple="multiple" size="5">
                                {% for tag in tags %}
                                <option value="{{tag.name}}">{{tag.name}}</option>
                                {% endfor %}
                            </select>
                        </label>
                    </div>
                    <div class="col-12">
                        <button type="submit" class="primary">Save</button>
                    </div>
                </div>
            </form>
        </div>

    </div>
</section>

{% endblock %}

app_notes/templates/app_notes/notes.html
{% extends 'app_main/base.html' %}

{% block notes %}
{% load static %}

<section id="five" class="wrapper style1 fade-up" xmlns="http://www.w3.org/1999/html">
    <div class="inner">
        <h2>Notes</h2>
        <div>
            <a href="{% url 'app_notes:note' %}" class="button">Add Note</a>
            <a href="{% url 'app_notes:tag' %}" class="button">Add Tag</a>
        </div>
        <br>

        <div class="row gtr-uniform">
            <form method="GET" action="{% url 'app_notes:search' %}" class="mb-4 border p-3">
                <div class="col-6">
                    <div class="row gtr-uniform">
                        <div class="col-6 col-12-xsmall">
                            <input type="text" name="query" class="form-control" placeholder="Search notes..." required>
                        </div>
                        <div class="col-6 col-12-xsmall">
                            <button type="submit" class="button primary">Search</button>
                        </div>
                    </div>
                </div>
            </form>

            <form method="GET" action="{% url 'app_notes:sort' %}" class="mb-4 border p-3">
                {% csrf_token %}
                <div class="col-12">
                    <div class="row gtr-uniform">
                        <div class="col-6">
                            <select class="form-select" aria-label="Default select example" name="selected_tags">
                                <option selected></option>
                                {% for tag in tags.all %}
                                <option value='{{ tag.name }}'>{{ tag.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="col-6">
                            <button type="submit" class="button primary">Filter</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>

        <div class="box alt">
            <div class="row gtr-uniform">
                {% for note in notes %}
                <div class="col-4"> <!-- Один блок по три в ряд -->
                    <div class="card mb-3"> <!-- Додайте клас mb-3 для відступу між картками -->
                        <div class="card-body">
                            <h3 class="card-title">{{ note.title }}</h3> <!-- Виправлено помилку в назві -->
                            <p class="card-text">{{ note.body }}</p>
                            <div class="row">
                                <div class="col">
                                    {% if not note.is_done %}
                                    <a href="{% url 'app_notes:set_done' note.id %}">
                                        <svg class="card-icon" xmlns="http://www.w3.org/2000/svg" height="20px"
                                             viewBox="0 0 448 512">
                                            <path d="M64 32C28.7 32 0 60.7 0 96V416c0 35.3 28.7 64 64 64H384c35.3 0 64-28.7 64-64V96c0-35.3-28.7-64-64-64H64zM337 209L209 337c-9.4 9.4-24.6 9.4-33.9 0l-64-64c-9.4-9.4-9.4-24.6 0-33.9s24.6-9.4 33.9 0l47 47L303 175c9.4-9.4 24.6-9.4 33.9 0s9.4 24.6 0 33.9z"/>
                                        </svg>
                                    </a>
                                    {% else %}
                                    <svg class="done-icon" xmlns="http://www.w3.org/2000/svg" height="20px"
                                         viewBox="0 0 512 512">
                                        <path d="M369 209L241 337c-9.4 9.4-24.6 9.4-33.9 0l-64-64c-9.4-9.4-9.4-24.6 0-33.9s24.6-9.4 33.9 0l47 47L335 175c9.4-9.4 24.6-9.4 33.9 0s9.4 24.6 0 33.9z"/>
                                    </svg>
                                    {% endif %}
                                </div>
                                <div class="col">
                                    <a href="{% url 'app_notes:detail' note.id %}">
                                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24"
                                             height="20px">
                                            <path fill="none" d="M0 0h24v24H0z"/>
                                            <path d="M12 17.27L18.18 12 12 6.73 11 7.8l4.2 4.2-4.2 4.2 1 1.07zM12 4C6.48 4 2 6.69 2 10s4.48 6 10 6 10-2.69 10-6-4.48-6-10-6zm0 10c-3.58 0-6-1.79-6-4s2.42-4 6-4 6 1.79 6 4-2.42 4-6 4z"/>
                                        </svg>
                                    </a>
                                </div>
                                <div class="col">
                                    <a href="{% url 'app_notes:edit_note' note.id %}"
                                       class="btn btn-outline-info btn-sm">
                                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24"
                                             height="20px">
                                            <path fill="none" d="M0 0h24v24H0z"/>
                                            <path d="M19.71 7.04l-2.83-2.83c-.19-.19-.45-.29-.71-.29s-.52.1-.71.29L3.79 16.74a1 1 0 0 0-.29.71v3.76a1 1 0 0 0 1 1H8a1 1 0 0 0 .71-.29l12.5-12.5a1 1 0 0 0 .29-.71V7.75a1 1 0 0 0-.29-.71zM7.08 20H5v-2.08l10.92-10.92 2.08 2.08L7.08 20zm10.44-9.48l-2.08-2.08l1.52-1.52l2.08 2.08l-1.52 1.52z"/>
                                        </svg>
                                    </a>
                                </div>
                                <div class="col">
                                    <a href="{% url 'app_notes:delete' note.id %}">
                                        <svg class="card-icon" xmlns="http://www.w3.org/2000/svg" height="20px"
                                             viewBox="0 0 448 512">
                                            <path d="M135.2 17.7L128 32H32C14.3 32 0 46.3 0 64S14.3 96 32 96H416c17.7 0 32-14.3 32-32s-14.3-32-32-32H320l-7.2-14.3C307.4 6.8 296.3 0 284.2 0H163.8c-12.1 0-23.2 6.8-28.6 17.7zM416 128H32L53.2 467c1.6 25.3 22.6 45 47.9 45H346.9c25.3 0 46.3-19.7 47.9-45L416 128z"/>
                                        </svg>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>

    </div>
</section>

{% endblock %}

app_notes/templates/app_notes/search_results.html
{% extends 'app_main/base.html' %}

{% block notes %}
{% if user.is_authenticated %}
<section id="five" class="wrapper style1 fade-up">
    <div class="inner">
        <h2>Search Results</h2>

        <a href="/app_notes" class="button small">to the list of notes</a>
        <p></p>

        <div class="box alt">
            <div class="row gtr-uniform">
                {% if notes %}
                {% for note in notes %}
                {% if not note.is_done %}
                <div class="col-4"> <!-- Один блок по три в ряд -->
                    <div class="card mb-3"> <!--  клас mb-3 для відступу між картками -->
                        <div class="card-body">
                            <h5 class="card-title">{{ note.title }}</h5>
                            <p class="card-text">{{ note.body }}</p>
                            <div class="row">
                                 <div class="col">
                                    <a href="{% url 'app_notes:set_done' note.id %}">
                                        <svg class="card-icon" xmlns="http://www.w3.org/2000/svg" height="20px"
                                             viewBox="0 0 448 512">
                                            <path d="M64 32C28.7 32 0 60.7 0 96V416c0 35.3 28.7 64 64 64H384c35.3 0 64-28.7 64-64V96c0-35.3-28.7-64-64-64H64zM337 209L209 337c-9.4 9.4-24.6 9.4-33.9 0l-64-64c-9.4-9.4-9.4-24.6 0-33.9s24.6-9.4 33.9 0l47 47L303 175c9.4-9.4 24.6-9.4 33.9 0s9.4 24.6 0 33.9z"/>
                                        </svg>
                                    </a>
                                 </div>
                                <div class="col">
                                    <a href="{% url 'app_notes:detail' note.id %}">
                                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24"
                                             height="20px">
                                            <path fill="none" d="M0 0h24v24H0z"/>
                                            <path d="M12 17.27L18.18 12 12 6.73 11 7.8l4.2 4.2-4.2 4.2 1 1.07zM12 4C6.48 4 2 6.69 2 10s4.48 6 10 6 10-2.69 10-6-4.48-6-10-6zm0 10c-3.58 0-6-1.79-6-4s2.42-4 6-4 6 1.79 6 4-2.42 4-6 4z"/>
                                        </svg>
                                    </a>
                                </div>
                                <div class="col">
                                    <a href="{% url 'app_notes:edit_note' note.id %}"
                                       class="btn btn-outline-info btn-sm">
                                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24"
                                             height="20px">
                                            <path fill="none" d="M0 0h24v24H0z"/>
                                            <path d="M19.71 7.04l-2.83-2.83c-.19-.19-.45-.29-.71-.29s-.52.1-.71.29L3.79 16.74a1 1 0 0 0-.29.71v3.76a1 1 0 0 0 1 1H8a1 1 0 0 0 .71-.29l12.5-12.5a1 1 0 0 0 .29-.71V7.75a1 1 0 0 0-.29-.71zM7.08 20H5v-2.08l10.92-10.92 2.08 2.08L7.08 20zm10.44-9.48l-2.08-2.08l1.52-1.52l2.08 2.08l-1.52 1.52z"/>
                                        </svg>
                                    </a>
                                </div>
                                <div class="col">
                                    <a href="{% url 'app_notes:delete' note.id %}">
                                        <svg class="card-icon" xmlns="http://www.w3.org/2000/svg" height="20px"
                                             viewBox="0 0 448 512">
                                            <path d="M135.2 17.7L128 32H32C14.3 32 0 46.3 0 64S14.3 96 32 96H416c17.7 0 32-14.3 32-32s-14.3-32-32-32H320l-7.2-14.3C307.4 6.8 296.3 0 284.2 0H163.8c-12.1 0-23.2 6.8-28.6 17.7zM416 128H32L53.2 467c1.6 25.3 22.6 45 47.9 45H346.9c25.3 0 46.3-19.7 47.9-45L416 128z"/>
                                        </svg>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% else %}
                <!-- Якщо нотатка вже виконана -->
                <div class="col-4"> <!-- Один блок по три в ряд -->
                    <div class="card mb-3"> <!--  mb-3 для відступу між картками -->
                        <div class="card-body">
                            <h5 class="card-title">{{ note.title }}</h5>
                            <p class="card-text">{{ note.body }}</p>
                            <div class="row">
                                <div class="col">
                                <svg class="done-icon" xmlns="http://www.w3.org/2000/svg" height="20px"
                                         viewBox="0 0 512 512">
                                        <path d="M369 209L241 337c-9.4 9.4-24.6 9.4-33.9 0l-64-64c-9.4-9.4-9.4-24.6 0-33.9s24.6-9.4 33.9 0l47 47L335 175c9.4-9.4 24.6-9.4 33.9 0s9.4 24.6 0 33.9z"/>
                                    </svg> <!--  позначки виконаної нотатки -->
                                 </div>
                                <div class="col">
                                    <a href="{% url 'app_notes:detail' note.id %}">
                                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24"
                                             height="20px">
                                            <path fill="none" d="M0 0h24v24H0z"/>
                                            <path d="M12 17.27L18.18 12 12 6.73 11 7.8l4.2 4.2-4.2 4.2 1 1.07zM12 4C6.48 4 2 6.69 2 10s4.48 6 10 6 10-2.69 10-6-4.48-6-10-6zm0 10c-3.58 0-6-1.79-6-4s2.42-4 6-4 6 1.79 6 4-2.42 4-6 4z"/>
                                        </svg>
                                    </a>
                                </div>
                                <!-- клас кнопки -->
                                <div class="col">
                                    <a href="{% url 'app_notes:delete' note.id %}">
                                        <svg class="card-icon" xmlns="http://www.w3.org/2000/svg" height="20px"
                                             viewBox="0 0 448 512">
                                            <path d="M135.2 17.7L128 32H32C14.3 32 0 46.3 0 64S14.3 96 32 96H416c17.7 0 32-14.3 32-32s-14.3-32-32-32H320l-7.2-14.3C307.4 6.8 296.3 0 284.2 0H163.8c-12.1 0-23.2 6.8-28.6 17.7zM416 128H32L53.2 467c1.6 25.3 22.6 45 47.9 45H346.9c25.3 0 46.3-19.7 47.9-45L416 128z"/>
                                        </svg>
                                    </a>
                                </div>
                                <!--  клас кнопки -->
                            </div>
                        </div>
                    </div>
                </div>
                {% endif %}
                {% endfor %}
                {% else %}
                <p class="text-center">No notes found.</p>
                {% endif %}
            </div>
        </div>
        <br>

        {% else %}
        <div style="text-align: center;">
            <h2>Sign up or login to your account!</h2>
        </div>
        {% endif %}

    </div>
</section>

{% endblock %}

app_notes/templates/app_notes/tag.html
{% extends 'app_main/base.html' %}

{% block notes %}
{% load static %}

<section id="five" class="wrapper style1 fade-up">
    <div class="inner">
        <h2>Add a Tag</h2>

        <a href="/app_notes" class="button small">to the list of notes</a>

        <div class="form-block">
            <br>
            <div class="text-center">
                <form method="POST" action="{% url 'app_notes:tag' %}">
                    <div class="row gtr-uniform">
                        {% csrf_token %}
                        <div class="col-6">
                            <label>Enter the Tag Name:
                                {{form.name}}
                            </label>
                        </div>
                    </div>
                    <span>{{ form.errors.name }}</span>
                    <div class="col-12">
                        <br>
                        <button type="submit" class="primary">Save</button>
                    </div>
                </form>
            </div>
        </div>

    </div>
</section>

{% endblock %}