NeuroContact/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app_main.urls")),
    path("users/", include("users.urls")),
    path("app_predict/", include("app_predict.urls")),
    path("app_contacts/", include("app_contacts.urls")),
    path("app_notes/", include("app_notes.urls")),
    path("app_files/", include("app_files.urls")),
    path("app_news/", include("app_news.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_files/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "app_files"

urlpatterns = [
    path("", views.main, name="files_page"),
    path("upload/", views.upload_file, name="upload_files"),
    path("image/", views.images, name="image_files"),
    path("video/", views.videos, name="video_files"),
    path("audio/", views.audios, name="audio_files"),
    path("document/", views.docs, name="docs_files"),
    path("archive/", views.archives, name="archives"),
    path("other/", views.other, name="other_files"),

    path("delete-file/<int:f_id>", views.delete_file, name='delete_file'),
    path("edit-description/<int:f_id>", views.edit_description, name='edit_description'),
]

app_main/urls.py
from django.urls import path, include

from . import views

app_name = "app_main"

urlpatterns = [
    path("", views.main, name="root"),  # app_main:root
    path("app_main/about_team/", views.about_team, name="about_team"),
    path(
        "app_main/about_application/", views.about_application, name="about_application"
    ),
]

app_news/urls.py
from django.urls import path, include

from . import views

app_name = "app_news"

urlpatterns = [
    path("", views.main, name="news_page"),
    path('sport-news/', views.sport_news, name='sport_news'),
    path('politic-news/', views.politic_news, name='politic_news'),
    path('culture-news/', views.culture_news, name='culture_news'),
]

app_notes/urls.py
from django.urls import path, include

from . import views

app_name = "app_notes"

urlpatterns = [
    path("", views.main, name="notes"),
    path("tag/", views.tag, name="tag"),
    path("note/", views.note, name="note"),
    path("detail/<int:note_id>", views.detail, name="detail"),
    path("done/<int:note_id>", views.set_done, name="set_done"),
    path("delete/<int:note_id>", views.delete_note, name="delete"),
    path('edit/<int:note_id>', views.edit_note, name='edit_note'),
    path('search/', views.search, name='search'),
    path('sort/', views.sort, name='sort'),
]

app_predict/urls.py
from django.urls import path, include

from . import views

app_name = "app_predict"

urlpatterns = [
    path("", views.main, name="image_predict"),
]

users/urls.py
from django.urls import path, include
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

from . import views
from .forms import LoginForm

app_name = "users"

urlpatterns = [
    path(
        "signup/",
        views.RegisterView.as_view(),
        name="signup",
    ),
    path(
        "signin/",
        LoginView.as_view(template_name="users/signin.html", form_class=LoginForm),
        name="signin",
    ),
    path(
        "signout/",
        LogoutView.as_view(template_name="users/signout.html"),
        name="signout",
    ),
    path("reset-password/", views.ResetPasswordView.as_view(), name="password_reset"),
    path(
        "reset-password/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset-password/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url="/users/reset-password/complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset-password/complete/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

app_main/models.py
from django.db import models

# Create your models here.

app_main/views.py
import requests
import environ

from datetime import date
from django.shortcuts import render

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)


def main(request):
    API_WEATHER_KEY = env("API_WEATHER_KEY")
    ABSTRACT_API_KEY = env("ABSTRACT_API_KEY")

    url_1 = (
        "https://api.openweathermap.org/data/2.5/weather?q={}&units=metric&appid="
        + API_WEATHER_KEY
    )

    response_ip = requests.get("https://api.ipify.org?format=json")
    if response_ip.status_code == 200:
        public_ip = response_ip.json()["ip"]
    else:
        public_ip = None
    # print(public_ip)

    if public_ip:
        response_city = requests.get(
            "https://ipgeolocation.abstractapi.com/v1/?api_key="
            + ABSTRACT_API_KEY
            + "&ip_address="
            + public_ip
        )
        # print(response_ip.status_code)
        # print(response_ip.content)
        if response_city.status_code == 200:
            data = response_city.json()
            city_temp = data["city"]
            if city_temp:
                city = city_temp
            else:
                city = "Kyiv"
        else:
            city = "Kyiv"
    else:
        city = "Kyiv"

    # city = "Kyiv"

    city_weather = requests.get(url_1.format(city)).json()

    weather = {
        "city": city,
        "temperature": city_weather["main"]["temp"],
        "description": city_weather["weather"][0]["description"],
        "icon": city_weather["weather"][0]["icon"],
        "temperature_max": city_weather["main"]["temp_max"],
        "temperature_min": city_weather["main"]["temp_min"],
        "feelslike_weather": city_weather["main"]["feels_like"],
    }

    url_2 = f"https://api.privatbank.ua/p24api/exchange_rates?json&date={date.today().strftime('%d.%m.%Y')}"

    currency_exchange = requests.get(url_2).json()

    exchange_rates = {}
    for item in currency_exchange["exchangeRate"]:
        currency = item["currency"]
        if currency in ["USD", "EUR"]:
            if date.today().strftime("%d.%m.%Y") not in exchange_rates:
                exchange_rates[date.today().strftime("%d.%m.%Y")] = {}
            exchange_rates[date.today().strftime("%d.%m.%Y")][currency] = {
                "sale": float(item["saleRate"]),
                "purchase": float(item["purchaseRate"]),
            }

    return render(
        request,
        "app_main/index.html",
        {"weather": weather, "exchange_rates": exchange_rates},
    )


def about_team(request):
    return render(request, "app_main/about_team.html", context={})


def about_application(request):
    return render(request, "app_main/about_application.html", context={})

app_main/templates/app_main/about_application.html
{% extends 'app_main/base.html' %}

{% block intro %}
{% load static %}

<section id="app_cloudy" class="wrapper style3 fade-up" xmlns="http://www.w3.org/1999/html">
    <div class="inner">
        <h2>What is NeuroContact and how it works</h2>
        <p>Web application built with the Django framework that provides users with tools to manage contacts and notes,
            upload files to cloud storage, and receive news summaries. The application includes authentication
            mechanisms to ensure the privacy and security of user data.</p>
        <div class="features">
            <section>
                <span class="icon solid major fa-laptop-code"></span>
                <h3>Technologies used</h3>
                <div style="overflow:auto;">
                    <div style="float:left;">
                        <h4><u>Front-end</u></h4>
                        <img src="{% static 'app_main/img_about/html-five.svg' %}" style="width: 20px; height: 20px;"/>
                        HTML
                        <br>
                        <img src="{% static 'app_main/img_about/css3-logo.svg' %}" style="width: 20px; height: 20px;"/>
                        CSS
                        <br>
                        <img src="{% static 'app_main/img_about/js.svg' %}" style="width: 20px; height: 20px;"/>
                        JavaScript
                    </div>
                    <div style="float:right;">
                        <h4><u>Back-end</u></h4>
                        <img src="{% static 'app_main/img_about/python.svg' %}" style="width: 20px; height: 20px;"/>
                        Python
                        <br>
                        <img src="{% static 'app_main/img_about/django.svg' %}" style="width: 20px; height: 20px;"/>
                        Django
                        <br>
                        <img src="{% static 'app_main/img_about/pgsql.svg' %}" style="width: 20px; height: 20px;"/>
                        PostgreSQL
                    </div>
                </div>
                <p></p>
                <div style="overflow:auto;">
                    <div style="float:left;">
                        <h4><u>Utilites</u></h4>
                        <img src="{% static 'app_main/img_about/jb-pycharm.svg' %}" style="width: 20px; height: 20px;"/>
                        PyCharm
                        <br>
                        <img src="{% static 'app_main/img_about/vscode.svg' %}" style="width: 20px; height: 20px;"/>
                        VS Code
                        <br>
                        <img src="{% static 'app_main/img_about/trello-logo.svg' %}"
                             style="width: 20px; height: 20px;"/>
                        Trello
                        <br>
                        <img src="{% static 'app_main/img_about/github-octocat.svg' %}"
                             style="width: 20px; height: 20px;"/>
                        GitHub
                    </div>
                    <div style="float:right;">
                        <h4><u>and...</u></h4>
                        <p></p>
                        <img src="{% static 'app_main/img_about/teamwork.svg' %}" style="width: 20px; height: 20px;"/>
                        Teamwork
                    </div>
                </div>
            </section>
            <section>
                <span class="icon solid major fa-user"></span>
                <h3>User authentication</h3>
                The application has an authentication mechanism:
                <ul>
                    <li>the web interface provides access to its functions only to registered users;</li>
                    <li>each registered user has access only to their own data and files;</li>
                    <li>implemented a password recovery mechanism for users by email.</li>
                    Data is validated during the registration of a new user.
                </ul>
            </section>
            <section>
                <span class="icon solid major fa-address-card"></span>
                <h3>Contacts</h3>
                An authorized user using the application can:
                <ul>
                    <li>save contacts with names, addresses, phone numbers, emails, birthdays and etc. to the contact book;
                    </li>
                    <li>display a list of contacts whose birthday is within a specified number of days from the current
                        date;
                    </li>
                    <li>search for contacts among the contacts in the directory;</li>
                    <li>edit and delete entries from the contact book;</li>
                    <li>shows upcoming birthdays of contacts.</li>
                    The application validates the contact data when creating or editing an entry and notifies the user
                    in case of incorrect entry.
                </ul>
            </section>
            <section>
                <span class="icon solid major fa-paperclip"></span>
                <h3>Notes</h3>
                An authorized user using the application can:
                <ul>
                    <li>store notes with text information;</li>
                    <li>search notes;</li>
                    <li>edit and delete notes;</li>
                    <li>add 'tags' to notes (keywords describing the topic and subject of the record);</li>
                    <li>search and sort notes by keywords (tags).</li>
                </ul>
            </section>
            <section>
                <span class="icon solid major fa-cloud"></span>
                <h3>Files</h3>
                An authorized user using the application can:
                <ul>
                    <li>upload files to the <a href="https://cloudinary.com" target="_blank" rel="nofollow noopener noreferrer">Cloudinary</a> service and access them;</li>
                    <li>download files from the <a href="https://cloudinary.com" target="_blank" rel="nofollow noopener noreferrer">Cloudinary</a> service;</li>
                    <li>sort/filter files by category (images, documents, videos, etc.);</li>
                </ul>
            </section>
            <section>
                <span class="icon major fa-newspaper"></span>
                <h3>News</h3>
                An authorized user using the application can:
                <ul>
                    <li>View a summary of the day's news.
                        Namely, select one of the proposed categories of news (sports, culture or politics), and the
                        application will show the headlines of the latest news, with the ability to go to the resource
                        with the news.
                    </li>
                </ul>
            </section>
        </div>
    </div>
</section>

{% endblock %}

app_main/templates/app_main/about_team.html
{% extends 'app_main/base.html' %}

{% block intro %}
{% load static %}

<section id="about" class="wrapper style2 spotlights">
    <section>
        <a href="https://github.com/CodeCraftSerg" class="image" target="_blank" rel="nofollow noopener noreferrer">
            <img src="{% static 'app_main/img_team/Serhii.jpg' %}" alt="Serhii" data-position="center center"/>
            <!--<img src="{% static 'app_main/images/pic01.jpg' %}" alt="Serhii" data-position="center center"/>-->
        </a>
        <div class="content">
            <div class="inner">
                <h2>Serhii</h2>
                <p>Team Lead of the project.
                    Developed the project's structure, starting template, and user authorization. Finalized the
                    front-end adaptation of the application.
                </p>
                <ul class="actions">
                    <li>
                        <a href="https://github.com/CodeCraftSerg" class="button" target="_blank" rel="nofollow noopener noreferrer">
                            GitHub
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </section>
    <section>
        <a href="https://github.com/HelgaTsar" class="image" target="_blank" rel="nofollow noopener noreferrer">
            <img src="{% static 'app_main/img_team/Olha.jpg' %}" alt="Olha" data-position="top center"/>
            <!--<img src="{% static 'app_main/images/pic02.jpg' %}" alt="Olha" data-position="top center"/>-->
        </a>
        <div class="content">
            <div class="inner">
                <h2>Olha</h2>
                <p>Scrum Master of the project.
                    Organized team meetings and developed the news section.</p>
                <ul class="actions">
                    <li>
                        <a href="https://github.com/HelgaTsar" class="button" target="_blank" rel="nofollow noopener noreferrer">
                            GitHub
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </section>
    <section>
        <a href="https://github.com/ShuguruiUA" class="image" target="_blank" rel="nofollow noopener noreferrer">
            <img src="{% static 'app_main/img_team/Iurii.jpg' %}" alt="Iurii" data-position="25% 25%"/>
            <!--<img src="{% static 'app_main/images/pic03.jpg' %}" alt="Iurii" data-position="25% 25%"/>-->
        </a>
        <div class="content">
            <div class="inner">
                <h2>Iurii</h2>
                <p>Project developer.
                    Developed the contacts section for users.</p>
                <ul class="actions">
                    <li>
                        <a href="https://github.com/ShuguruiUA" class="button" target="_blank" rel="nofollow noopener noreferrer">
                            GitHub
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </section>
    <section>
        <a href="https://github.com/Krisiris250592" class="image" target="_blank" rel="nofollow noopener noreferrer">
            <img src="{% static 'app_main/img_team/Kris.jpg' %}" alt="Kris" data-position="center center"/>
            <!--<img src="{% static 'app_main/images/pic04.jpg' %}" alt="Kris" data-position="center center"/>-->
        </a>
        <div class="content">
            <div class="inner">
                <h2>Kris</h2>
                <p>Project developer.
                    Developed the notes section for users.</p>
                <ul class="actions">
                    <li>
                        <a href="https://github.com/Krisiris250592" class="button" target="_blank" rel="nofollow noopener noreferrer">
                            GitHub
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </section>
    <section>
        <a href="https://github.com/xrendezvous" class="image" target="_blank" rel="nofollow noopener noreferrer">
            <img src="{% static 'app_main/img_team/Aryna.jpg' %}" alt="Aryna" data-position="top center"/>
            <!--<img src="{% static 'app_main/images/pic05.jpg' %}" alt="Aryna" data-position="top center"/>-->
        </a>
        <div class="content">
            <div class="inner">
                <h2>Aryna</h2>
                <p>Project developer.
                    Developed the files upload/download/sort section for users.</p>
                <ul class="actions">
                    <li>
                        <a href="https://github.com/xrendezvous" class="button" target="_blank" rel="nofollow noopener noreferrer">
                            GitHub
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </section>
</section>

{% endblock %}

app_main/templates/app_main/base.html
<!DOCTYPE HTML>
<html lang="en">
<head>
    <title>NeuroContact</title>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no"/>
    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{% static 'app_main/images/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'app_main/css/main.css' %}"/>
    <noscript>
        <link rel="stylesheet" href="{% static 'app_main/css/noscript.css' %}"/>
    </noscript>
    <link rel="stylesheet" href="{% static 'app_main/css/fontawesome-all.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'users/css/signout.css' %}"/>
    <link rel="stylesheet" href="{% static 'app_main/css/style.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'app_contacts/css/contact.css' %}"/>

</head>
<body class="is-preload">

<!-- Sidebar -->
<section id="sidebar">
    <div class="inner">
        <nav>
            <ul>
                {% if user.is_authenticated %}
                {% csrf_token %}
                <li><a href="{% url 'app_main:root' %}">Welcome</a></li>
                <li><a href="{% url 'app_predict:image_predict' %}">Image recognition</a></li>
                <li><a href="{% url 'app_contacts:contacts' %}">Contacts</a></li>
                <li><a href="{% url 'app_contacts:contact_birthday' %}">Birthdays</a></li>
                <li><a href="{% url 'app_notes:notes' %}">Notes</a></li>
                <li><a href="{% url 'app_files:files_page' %}">Files</a></li>
                <li><a href="{% url 'app_news:news_page' %}">News</a></li>
                <li>
                    <form method="post" action="{% url 'users:signout' %}">
                        {% csrf_token %}
                        <a class="submit" href="#">Sign Out</a>
                    </form>
                </li>
                {% else %}
                <li><a href="{% url 'app_main:root' %}">Welcome</a></li>
                <li><a href="{% url 'app_main:about_team' %}">About Team</a></li>
                <li><a href="{% url 'app_main:about_application' %}">About Application</a></li>
                <li><a href="{% url 'users:signin' %}">Sign In</a></li>
                <li><a href="{% url 'users:signup' %}">Sign Up</a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
</section>

<!-- Wrapper -->
<div id="wrapper">

    <!-- Intro -->
    {% block intro %}
    {% endblock %}

    <!-- Auth -->
    {% block auth %}
    {% endblock %}

    <!-- PasswordReset -->
    {% block reset %}
    {% endblock %}

    <!-- Image recognition -->
    {% block image_predict %}
    {% endblock %}

    <!-- Contacts -->
    {% block contacts %}
    {% endblock %}

    <!-- Notes -->
    {% block notes %}
    {% endblock %}

    <!-- Files Page -->
    {% block files_page %}
    {% endblock %}

    <!-- News Page -->
    {% block news_page %}
    {% endblock %}

</div>

<!-- Footer -->
<footer id="footer" class="wrapper style1-alt">
    <div class="inner">
        <ul class="menu">
            <li>&copy; The NeuroContact. All rights reserved.</li>
            <li>Design: <a href="{% url 'app_main:root' %}">The NeuroContact</a></li>
        </ul>
    </div>
</footer>

<!-- Scripts -->
<script src="{% static 'app_main/js/jquery.min.js' %}"></script>
<script src="{% static 'app_main/js/jquery.scrollex.min.js' %}"></script>
<script src="{% static 'app_main/js/jquery.scrolly.min.js' %}"></script>
<script src="{% static 'app_main/js/browser.min.js' %}"></script>
<script src="{% static 'app_main/js/breakpoints.min.js' %}"></script>
<script src="{% static 'app_main/js/util.js' %}"></script>
<script src="{% static 'app_main/js/main.js' %}"></script>
<script src="{% static 'app_main/js/skycons.js' %}"></script>
<script src="{% static 'app_news/news.js' %}"></script>
<script type="application/x-javascript"> addEventListener("load", function () {
    setTimeout(hideURLbar, 0);
}, false);

function hideURLbar() {
    window.scrollTo(0, 1);
} </script>

</body>
</html>

app_main/templates/app_main/index.html
{% extends 'app_main/base.html' %}

{% block intro %}
{% load static %}

<section id="intro" class="wrapper style1 fullscreen fade-up">
    <div class="inner">
        <h1>NeuroContact</h1>
        <p>NeuroContact is an application that allows you to store user contact information, notes, upload files to
            the cloud, and view news by category. To get started, please <a href="{% url 'users:signin' %}">sign in</a>
            or <a href="{% url 'users:signup' %}">sign up</a>.
        </p>

        <div class="grid-container">

            <div class="main-weather">
                <h2>Weather Now</h2>
                <div class="weather-info">
                    <div class="weather-current">
                        <h2>{{weather.city}}</h2>
                        <h3>Feels like {{weather.feelslike_weather}}°C</h3>
                    </div>
                    <div class="weather-icon">
                        <canvas id="clear-day" width="70" height="70"></canvas>
                        <img src="https://openweathermap.org/img/wn/{{weather.icon}}.png" alt="Image"
                             width="100px">
                    </div>
                    <div class="weather-temps">
                        <h4>Max {{weather.temperature_max}}°</h4>
                        <h2>{{weather.temperature}}°C</h2>
                        <h4>Min {{weather.temperature_min}}°</h4>
                    </div>
                </div>
            </div>

            <div class="main-currency">
                <h2>Exchange Rates</h2>
                <h4>(In the branches of Privatbank)</h4>
                <div class="currency-info">
                    {% for date, currencies in exchange_rates.items %}
                    <ul>
                        {% for currency, rate in currencies.items %}
                        <li><h3>{{ currency }}: {{ rate.purchase }} / {{ rate.sale }}</h3></li>
                        {% endfor %}
                    </ul>
                    {% endfor %}
                </div>
            </div>

        </div>

    </div>
</section>

{% endblock %}