NeuroContact/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app_main.urls")),
    path("users/", include("users.urls")),
    path("app_predict/", include("app_predict.urls")),
    path("app_contacts/", include("app_contacts.urls")),
    path("app_notes/", include("app_notes.urls")),
    path("app_files/", include("app_files.urls")),
    path("app_news/", include("app_news.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_contacts/urls.py
from django.urls import path

from . import views

app_name = "app_contacts"

urlpatterns = [
    path("", views.main, name="contacts"),
    path("<int:page>", views.main, name="index_paginate"),
    path("add_contact/", views.add_contact, name="add_contact"),
    path("contact_details/<int:contact_id>/", views.contact_details, name="contact_details"),
    path("delete_contact/<int:contact_id>/", views.delete_contact, name="delete_contact"),
    path("contact_update/<int:contact_id>/", views.contact_update, name="contact_update"),
    path("contact_birthday/", views.contact_birthday, name="contact_birthday"),
    path("calendar/", views.calendar, name="calendar"),

]

users/urls.py
from django.urls import path, include
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

from . import views
from .forms import LoginForm

app_name = "users"

urlpatterns = [
    path(
        "signup/",
        views.RegisterView.as_view(),
        name="signup",
    ),
    path(
        "signin/",
        LoginView.as_view(template_name="users/signin.html", form_class=LoginForm),
        name="signin",
    ),
    path(
        "signout/",
        LogoutView.as_view(template_name="users/signout.html"),
        name="signout",
    ),
    path("reset-password/", views.ResetPasswordView.as_view(), name="password_reset"),
    path(
        "reset-password/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset-password/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url="/users/reset-password/complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset-password/complete/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

app_contacts/models.py
from django.db import models
from django.contrib.auth.models import User

"""
Basic models for contacts
"""


# Create your models here.
class Contact(models.Model):
    name = models.CharField(max_length=20, unique=False, default="Name", null=False)
    surname = models.CharField(max_length=20, unique=False, default="Surname", null=False)
    email = models.EmailField(unique=False, null=True)
    mobile_phone = models.CharField(max_length=20, null=True, unique=False)
    work_phone = models.CharField(max_length=20, null=True, unique=False)
    home_phone = models.CharField(max_length=20, null=True, unique=False)
    birthdate = models.DateField(null=True, blank=True)
    is_favorite = models.BooleanField(default=False)
    facebook = models.URLField(null=True, blank=True)
    instagram = models.URLField(null=True, blank=True)
    tiktok = models.URLField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)

    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f"{self.name} {self.surname}"


class Address(models.Model):
    country = models.CharField(max_length=20, null=True)
    city = models.CharField(max_length=20, null=True)
    address = models.CharField(max_length=100, null=True)

    contact = models.ForeignKey(Contact, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f"{self.country} {self.city} {self.address}"

app_contacts/forms.py
from django.core.validators import RegexValidator
from django.forms import ModelForm, CharField, TextInput, DateInput, BooleanField, CheckboxInput, DateField, EmailField

from app_contacts.models import Contact, Address


class ContactForm(ModelForm):
    name = CharField(min_length=3, max_length=20, required=True,
                     widget=TextInput(attrs={'placeholder': "*Name"}))
    surname = CharField(min_length=3, max_length=20, required=False,
                        widget=TextInput(attrs={'placeholder': 'Surname'}))
    email = EmailField(required=False,
                      widget=TextInput(attrs={'placeholder': 'Email'}))
    mobile_phone = CharField(required=False, validators=[RegexValidator(
        regex=r'\+?\d{1,3}\(?\d{2,4}\)?\d{3}(?:-?\d{3,4})(\d{3})?',
        message='Phone number must be entered in the format: '
                '+CountryCode(operator code)phone number example: +380(50)1234567. Up to 15 digits allowed.'
    )],
                             widget=TextInput(attrs={'placeholder': 'Mobile phone', "class": "form-control"}))
    work_phone = CharField(required=False, validators=[RegexValidator(
        regex=r'\+?\d{1,3}\(?\d{2,4}\)?\d{3}(?:-?\d{3,4})(\d{3})?',
        message='Phone number must be entered in the format: '
                '+CountryCode(operator code)phone number example: +380(50)1234567. Up to 15 digits allowed.'
    )],
                           widget=TextInput(attrs={'placeholder': 'Work phone', "class": "form-control"}))
    home_phone = CharField(required=False, validators=[RegexValidator(
        regex=r'\+?\d{1,3}\(?\d{2,4}\)?\d{3}(?:-?\d{3,4})(\d{3})?',
        message='Phone number must be entered in the format: '
                '+CountryCode(operator code)phone number example: +380(50)1234567. Up to 15 digits allowed.'
    )],
                           widget=TextInput(attrs={'placeholder': 'Home phone', "class": "form-control"}))
    birthdate = DateField(required=False, input_formats=['%d/%m/%Y'], widget=DateInput(format='%d/%m/%Y'))
    facebook = CharField(required=False, validators=[RegexValidator(
        regex=r'^https?://(www\.)?facebook\.com/.+',
        message='Enter a valid Facebook URL.',
    )], widget=TextInput(attrs={'placeholder': 'https://facebook.com', "class": "form-control"}))
    instagram = CharField(required=False, validators=[RegexValidator(
        regex=r'^https?://(www\.)?instagram\.com/.+',
        message='Enter a valid Instagram URL.',
    )], widget=TextInput(attrs={"placeholder": 'https://instagram.com', "class": "form-control"}))
    tiktok = CharField(required=False, validators=[RegexValidator(
        regex=r'^https?://(www\.)?tiktok\.com/.+',
        message='Enter a valid Tiktok URL.',
    )], widget=TextInput(attrs={"placeholder": 'https://tiktok.com', "class": "form-control"}))
    is_favorite = BooleanField(required=False, label='Is favorite',
                               widget=CheckboxInput(attrs={'placeholder': 'is_favorite', "class": "form-check-input"}))

    class Meta:
        model = Contact
        fields = ['name', 'surname', 'email', 'mobile_phone', 'work_phone', 'home_phone', 'birthdate', 'is_favorite',
                  'facebook', 'instagram', 'tiktok', ]
        widgets = {
            'birthdate': DateInput(attrs={'type': 'date'}),
        }


class AddressForm(ModelForm):
    country = CharField(required=False, widget=TextInput(attrs={'placeholder': 'Country', "class": "form-control"}))
    city = CharField(required=False, widget=TextInput(attrs={'placeholder': 'City', "class": "form-control"}))
    address = CharField(required=False, widget=TextInput(attrs={'placeholder': 'Address', "class": "form-control"}))

    class Meta:
        model = Address
        fields = ['country', 'city', 'address']

app_contacts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.db.models import Q
from datetime import datetime, timedelta
from calendar import monthcalendar

from app_contacts.forms import ContactForm, AddressForm
from app_contacts.models import Contact, Address


@login_required
def main(request, page=1):
    contacts = (
        Contact.objects.filter(user=request.user).all().order_by("name") # noqa
        if request.user.is_authenticated
        else []
    )
    total_contacts = contacts.count() # noqa
    if not contacts:
        error_message = "You have no contacts"
    else:
        error_message = None
    query = request.GET.get("q")

    if query:
        contacts = Contact.objects.filter( # noqa
            Q(
                address__in=Address.objects.filter( # noqa
                    Q(country__icontains=query.strip())
                    | Q(city__icontains=query.strip())
                    | Q(address__icontains=query.strip())
                )
            )
            | Q(name__icontains=query.strip())
            | Q(surname__icontains=query.strip())
            | Q(email__icontains=query.strip())
            | Q(mobile_phone__icontains=query.strip())
            | Q(home_phone__icontains=query.strip())
            | Q(work_phone__icontains=query.strip())
            | Q(birthdate__icontains=query.strip())
        ).distinct()

        if not contacts:
            error_message = "No contacts found"
        else:
            error_message = None

    per_page = 10
    paginator = Paginator(contacts, per_page)
    page = request.GET.get("page", 1)
    try:
        contacts_on_page = paginator.page(page)
    except PageNotAnInteger:
        contacts_on_page = paginator.page(1)
    except EmptyPage:
        contacts_on_page = paginator.page(paginator.num_pages)

    return render(
        request,
        "app_contacts/contacts.html",
        context={
            "contacts": contacts_on_page,
            "error_message": error_message,
            "total_contacts": total_contacts,
        },
    )


@login_required
def add_contact(request):
    if request.method == "POST":
        form = ContactForm(request.POST)
        form2 = AddressForm(request.POST)

        if form.is_valid() and form2.is_valid():
            contact = form.save(commit=False)
            contact.user = request.user
            contact = form.save()

            address = form2.save(commit=False)
            address.contact = contact
            address.save()
            messages.success(
                request,
                f"Contact '{form.cleaned_data['name']}' {form.cleaned_data['surname']}' added",
            )
            return redirect(to="app_contacts:contacts")
        else:
            return render(
                request,
                "app_contacts/add_contact.html",
                context={"form": form, "form2": form2},
            )
    return render(
        request,
        "app_contacts/add_contact.html",
        context={"form": ContactForm(), "form2": AddressForm()},
    )


@login_required
def contact_details(request, contact_id):
    a = get_object_or_404(Contact, id=contact_id)
    b = get_object_or_404(Address, contact_id=contact_id)
    return render(
        request,
        "app_contacts/contact_details.html",
        context={"Title": "Contact details", "contact": a, "address": b},
    )


@login_required
def delete_contact(request, contact_id):
    try:
        a = get_object_or_404(Contact, id=contact_id)
        a.delete()
        messages.success(request, f"Contact '{a.name} {a.surname}' deleted")
        return redirect(to="app_contacts:contacts")
    except Contact.DoesNotExist: # noqa
        raise Http404("Contact not found")


@login_required
def contact_update(request, contact_id=None):
    a = None
    b = None

    if contact_id:
        a = get_object_or_404(Contact, id=contact_id)
        b = get_object_or_404(Address, contact_id=contact_id)

    if request.method == "POST":
        form = ContactForm(request.POST, instance=a)
        form2 = AddressForm(request.POST, instance=b)
        if form.is_valid() and form2.is_valid():
            contact = form.save(commit=False)
            contact.user = request.user
            contact = form.save()

            address = form2.save(commit=False)
            address.contact = contact
            address.save()
            if a:
                messages.success(
                    request,
                    f"Contact '{form.cleaned_data['name']} {form.cleaned_data['surname']}' updated",
                )
            else:
                messages.success(
                    request,
                    f"Contact '{form.cleaned_data['name']} {form.cleaned_data['surname']}' added",
                )
            # return redirect(reverse('app_contacts:contact_update', args=[contact_id]))
            return redirect(to="app_contacts:contact_details", contact_id=contact_id)
    else:
        form = ContactForm(
            instance=a,
            initial={"mobile_phone": a.mobile_phone, "birthdate": a.birthdate},
        )
    return render(
        request,
        "app_contacts/contact_update.html",
        context={"form": form, "contact": a, "address": b},
    )


@login_required
def contact_birthday(request):
    period = request.GET.get("period")

    today = datetime.now()
    current_month = today.month
    current_day = today.day
    passed_this_year = []
    today_birthdays = []
    upcoming_this_month = []

    if period == "today":
        contacts = Contact.objects.filter( # noqa
            birthdate__month=current_month,
            birthdate__day=current_day,
            user=request.user,
        )
    elif period == "week":
        start_date = today - timedelta(days=today.weekday())
        end_date = start_date + timedelta(days=6)
        current_year = today.year

        contacts = Contact.objects.filter( # noqa
            Q(birthdate__year=current_year) &
            Q(birthdate__month=start_date.month) | Q(birthdate__month=end_date.month),
            Q(birthdate__day__gte=start_date.day) & Q(birthdate__day__lte=end_date.day),
            user=request.user,
        )

    elif period == "month":
        passed_this_year = Contact.objects.filter( # noqa
            birthdate__month=current_month,
            birthdate__day__lt=current_day,
            user=request.user,
        )
        today_birthdays = Contact.objects.filter( # noqa
            birthdate__month=current_month,
            birthdate__day=current_day,
            user=request.user,
        )
        upcoming_this_month = Contact.objects.filter( # noqa
            birthdate__month=current_month,
            birthdate__day__gt=current_day,
            user=request.user,
        )
        contacts = []
    else:
        contacts = []

    context = {
        "passed_this_year": passed_this_year,
        "today_birthdays": today_birthdays,
        "upcoming_this_month": upcoming_this_month,
        "period": period,
        "birthday_contacts": contacts,
    }
    return render(request, "app_contacts/contact_birthday.html", context=context)


@login_required
def calendar(request):
    year = request.GET.get('year')
    month = request.GET.get('month')

    today = datetime.now()
    day_today = today.day

    if month is None or year is None:
        year = today.year
        month = today.month

    month = int(month)
    year = int(year)

    cal_date = monthcalendar(year, month)

    birthday_contacts = Contact.objects.filter( # noqa
        user=request.user,
        birthdate__month=month,
        birthdate__year__lte=year
    )
    context = {
        'day_today': day_today,
        'calendar': cal_date,
        'birthday_contacts': birthday_contacts
    }

    return render(request, 'app_contacts/calendar.html', context=context)

app_contacts/templates/app_contacts/add_contact.html
{% extends 'app_main/base.html' %}

{% block contacts %}
{% load static %}

<section id="five" class="wrapper style1 fade-up">
    <div class="inner">
        <h2>Add contact</h2>

        <a href="/app_contacts" class="button small">to the list of contacts</a>
        <br>
        <br>

        <div class="split style1">
            <section>
                {% if form.errors  %}
                <div class="alert alert-danger" role="alert">
                    Please correct the errors below.
                </div>
                {% endif %}
                {% if messages %}
                <div class="messages">
                    {% for message in messages %}
                        <span {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %}>
                            {{ message }}
                        </span>
                    {% endfor %}
                </div>
                {% endif %}
                <span style="font-size: 10pt">Fields marked '*' are required</span>
                <form method="post" action="{% url 'app_contacts:add_contact' %}">
                    {% csrf_token %}
                    <span>Input Name and Surname:</span>
                    <div class="row gtr-uniform">
                        <div class="col-6 col-12-xsmall">
                            <input type="text" style="form-class" placeholder="*Name" name="name">
                            <ul style="color: red; font-size: 14pt">{{ form.errors.name }}</ul>
                        </div>
                        <div class="col-6 col-12-xsmall">
                            <input type="text" style="form-class" placeholder="Surname" name="surname">
                        </div>
                    </div>
                    <span>Input Email:</span>
                    <div class="row gtr-uniform">
                        <div class="col-6 col-12-xsmall">
                            <input type="text" style="form-class" placeholder="name@email.com" name="email">
                            <ul style="color: red; font-size: 14pt">{{ form.errors.email }}</ul>
                        </div>
                    </div>
                    <span>Input Phone numbers:</span>
                    <div class="row gtr-uniform">
                        <div class="col-6 col-12-xsmall">
                           mobile<input type="text" style="form-class" placeholder="+380(XX)XXX-XX-XX" name="mobile_phone">
                           <ul style="color: red; font-size: 14pt">{{ form.errors.mobile_phone }}</ul>
                        </div>
                        <div class="col-6 col-12-xsmall">
                            work<input type="text" style="form-class" placeholder="+380(XX)XXX-XX-XX" name="work_phone">
                            <ul style="color: red; font-size: 14pt">{{ form.errors.work_phone }}</ul>
                        </div>
                        <div class="col-6 col-12-xsmall">
                            home<input type="text" style="form-class" placeholder="+380(XX)XXX-XX-XX" name="home_phone">
                            <ul style="color: red; font-size: 14pt">{{ form.errors.home_phone }}</ul>
                        </div>
                    </div>
                    <span>Input Birthday:</span>
                    <div class="row gtr-uniform">
                        <div class="col-6 col-12-xsmall">
                            <input type="text" class="form-control" placeholder="dd/mm/YYYY" name="birthdate">
                            <ul style="color: red; font-size: 14pt">{{ form.errors.birthdate }}</ul>
                        </div>
                    </div>
                    <span>Facebook</span>
                    <div class="row gtr-uniform">
                        <div class="col-6 col-12-xsmall">
                            <input type="text" class="form-control" placeholder="https://facebook.com/" name="facebook">
                            <ul style="color: red; font-size: 14pt">{{ form.errors.facebook }}</ul>
                        </div>
                    </div>
                    <span>Instagram</span>
                    <div class="row gtr-uniform">
                        <div class="col-6 col-12-xsmall">
                            <input type="text" class="form-control" placeholder="https://instagram.com/"
                                   name="instagram">
                            <ul style="color: red; font-size: 14pt">{{ form.errors.instagram }}</ul>
                        </div>
                    </div>
                    <span>Tiktok</span>
                    <div class="row gtr-uniform">
                        <div class="col-6 col-12-xsmall">
                            <input type="text" class="form-control" placeholder="https://tiktok.com/" name="tiktok">
                            <ul style="color: red; font-size: 14pt">{{ form.errors.tiktok }}</ul>
                        </div>
                    </div>

                    <span>Input Address:</span>
                    <div class="row gtr-uniform">

                        <div class="col-6 col-12-xsmall">
                            <input type="text" class="form-control" placeholder="Country" name="country">
                        </div>
                        <div class="col-6 col-12-xsmall">
                            <input type="text" class="form-control" placeholder="City" name="city">
                        </div>
                        <div class="col-6 col-12-xsmall">
                            <input type="text" class="form-control" placeholder="Address" name="address">
                        </div>
                    </div>
                    <div class="row gtr-uniform">
                        <div class="col-6 col-12-xsmall" style="margin-top: 1em">
                            <input id="is_favorite" type="checkbox" name="is_favorite">
                            <label class="form-label" for="is_favorite">Favorite</label>

                        </div>
                    </div>

                    <div class="row gtr-uniform" style="margin-top: 10px">
                        <div clas="col-6 col-12-xsmall" >
                            <button class="btn" type="submit">Save</button>
                        </div>
                        <div clas="col-6 col-12-xsmall" >
                            <a href="{% url 'app_contacts:add_contact' %}" class="button">Reset</a>
                        </div>
                        <div clas="col-6 col-12-xsmall" >
                            <a href="{% url 'app_contacts:contacts' %}" class="button">Back</a>
                        </div>
                    </div>
                </form>
            </section>
        </div>
    </div>
</section>

{% endblock %}

app_contacts/templates/app_contacts/contact_birthday.html
{% extends 'app_main/base.html' %}

{% block contacts %}
{% load static %}

{% if user.is_authenticated %}

<section id="intro" class="wrapper style1 fade-up">
    <div class="inner">
        <h2>Birthdays list</h2>
        <div>
            Current date: {% now "l, d/m/Y" %}

        </div>
        <div>Current time: {% now "H:i" %}</div>
        <form action="{% url 'app_contacts:contact_birthday' %}" method="GET">
            <label for="period">Select Period:</label>
            <select name="period" id="period" style="width: 70%">
                <option value="today" {% if period == "today" %}selected{% endif %}>Today</option>
                <option value="week" {% if period == "week" %}selected{% endif %}>This Week</option>
                <option value="month" {% if period == "month" %}selected{% endif %}>This Month</option>
            </select>
            <button type="submit" style="margin-top: 20px">Show</button>
        </form>
        {% if period == 'today' or period == 'week' %}
            {% if birthday_contacts %}
            <div class="row">
                <div class="col">
                    <h2>{{ period|capfirst }} Birthdays</h2>
                    <ul class="birthday-icon">
                        {% for contact in birthday_contacts %}
                            <li><a href="/app_contacts/contact_details/{{ contact.id }}/">
                                {{ contact.name }} - {{ contact.birthdate|date:"M d" }}
                            </a></li>
                        {% endfor %}
                    </ul>
                    {% else %}
                        <p>No birthdays found for this period: {{ period|capfirst }}.</p>
                    {% endif %}
                </div>
            </div>
        {% endif %}
        {% if period == 'month' %}
        {% if passed_this_year or today_birthdays or upcoming_this_month %}
        <div class="row">
            <div class="col">
                <h5>Passed Birthdays</h5>
                {% if not passed_this_year %}<div style="font-size: 14pt">No birthdays to show.</div>{% endif %}
                <ul class="birthday-icon-pass">
                    {% for contact in passed_this_year %}
                        <li><a href="/app_contacts/contact_details/{{ contact.id }}/">
                            {{ contact.name }} - {{ contact.birthdate|date:"M d" }}
                        </a></li>
                    {% endfor %}
                </ul>
            </div>
            <div class="col">
                <h5>Today's Birthdays</h5>
                {% if not today_birthdays %}<div style="font-size: 14pt">No birthdays to show.</div>{% endif %}
                <ul class="birthday-icon">
                    {% for contact in today_birthdays %}
                        <li><a href="/app_contacts/contact_details/{{ contact.id }}/">
                            {{ contact.name }} - {{ contact.birthdate|date:"M d" }}
                        </a></li>
                    {% endfor %}
                </ul>
            </div>
            <div class="col">
                <h5>Upcoming Birthdays</h5>
                {% if not upcoming_this_month %}<div style="font-size: 14pt">No birthdays to show.</div>{% endif %}
                <ul class="birthday-icon">
                    {% for contact in upcoming_this_month %}
                        <li><a href="/app_contacts/contact_details/{{ contact.id }}/">
                            {{ contact.name }} - {{ contact.birthdate|date:"M d" }}
                        </a></li>
                    {% endfor %}
                </ul>
            </div>
            <br>

        </div>
        <div class="col-6">
            <a href="{% url 'app_contacts:calendar' %}" class="button small">View as calendar</a>
        </div>
        {% else %}
            <p>No birthdays found for this period: {{ period|capfirst}}.</p>
        {% endif %}
    </div>
</section>
{% endif %}
{% endif %}
{% endblock %}

app_contacts/templates/app_contacts/contact_details.html
{% extends 'app_main/base.html' %}

{% block contacts %}
{% load static %}

<section id="five" class="wrapper style1 fade-up">
    <div class="inner">
        <h2>Contact details:</h2>

        {% if messages %}
        <div class="messages">
            {% for message in messages %}
            <span {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %}>{{ message }}</span>
            {% endfor %}
        </div>
        {% endif %}
        <h3>
            {% if contact.is_favorite %}
            <div>
                <img src="{% static 'app_main/images/favorite-ico.svg' %}" style="width: 20px; height: 20px;"/>
                {{contact.name}} {{contact.surname}}
            </div>
            {% else %}
            <div>
                <img src="{% static 'app_main/images/favorite-blank-ico.svg' %}"
                     style="width: 20px; height: 20px;"/> {{contact.name}} {{contact.surname}}
            </div>
            {% endif %}
        </h3>

        {% if contact.birthdate %}
        <div>
            <img src="{% static 'app_main/images/birthday-ico.svg' %}"
                 style="width: 20px; height: 20px;"/> {{contact.birthdate}}
        </div>
        {% endif %}
        {% if contact.email %}
        <div>
            <a href="mailto:{{contact.email}}" target="_blank">
                <img src="{% static 'app_main/images/email-ico.svg' %}" style="width: 20px; height: 20px;"/> </a>
            {{contact.email}}
        </div>
        {% endif %}
        {% if contact.mobile_phone %}
        <div>
            <img src="{% static 'app_main/images/mobile-ico.svg' %}" style="width: 20px; height: 20px;"/> Mobile:
            {{contact.mobile_phone}}
        </div>
        {% endif %}
        {% if contact.work_phone %}
        <div>
            <img src="{% static 'app_main/images/phone-ico.svg' %}" style="width: 20px; height: 20px;"/> Work:
            {{contact.work_phone}}
        </div>
        {% endif %}
        {% if contact.home_phone %}
        <div>
            <img src="{% static 'app_main/images/phone-ico.svg' %}" style="width: 20px; height: 20px;"/> Home:
            {{contact.home_phone}}
        </div>
        {% endif %}
        <div>
            {% if contact.facebook %}
            <a href="{{contact.facebook}}" target="_blank"><img src="{% static 'app_main/images/facebook-ico.svg' %}"
                                                                style="width: 20px; height: 20px;"/></a>
            {% endif %}
            {% if contact.instagram %}
            <a href="{{contact.instagram}}" target="_blank"><img src="{% static 'app_main/images/instagram-ico.svg' %}"
                                                                 style="width: 20px; height: 20px;"/></a>
            {% endif %}
            {% if contact.tiktok %}
            <a href="{{contact.tiktok}}" target="_blank"><img
                    src="{% static 'app_main/images/tiktok-ico.svg' %}"
                    style="width: 20px; height: 20px;"/></a>
            {% endif %}
        </div>
        <div>
            {% if address.address or address.city or address.country %}
            <a href="https://www.google.com/maps/search/
            {% if address.country %}{{address.country}}+{% endif %}
            {% if address.city %}{{address.city}}+{% endif %}
            {% if address.address %} {{address.address}}{% endif %}/"
               target="_blank">
                <img src="{% static 'app_main/images/address-ico.svg' %}" style="width: 20px; height: 20px;"/></a>
            {% endif %}

            {% if address.address %}
            {{address.address}}
            {% endif %}

            {% if address.city %}
            {{address.city}}
            {% endif %}

            {% if address.country %}
            {{address.country}}
            {% endif %}
            <p></p>
        </div>

        <nav>
            <div style="display: flex; align-items: center;">
                <div clas="col-6 col-12-xsmall">
                    {% csrf_token %}
                    <a href="{% url 'app_contacts:contact_update' contact.id %}" class="button">
                        Update
                    </a>
                </div>
                <div clas="col-6 col-12-xsmall" style="margin-right: 2%; margin-left: 2%">
                    {% csrf_token %}
                    <a href="{% url 'app_contacts:delete_contact' contact.id %}" class="button">
                        Delete
                    </a>
                </div>
                <div clas="col-6 col-12-xsmall">
                    <a href="{% url 'app_contacts:contacts' %}" class="button">
                        Back
                    </a>
                </div>
            </div>
        </nav>

    </div>
</section>

{% endblock %}