NeuroContact/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app_main.urls")),
    path("users/", include("users.urls")),
    path("app_predict/", include("app_predict.urls")),
    path("app_contacts/", include("app_contacts.urls")),
    path("app_notes/", include("app_notes.urls")),
    path("app_files/", include("app_files.urls")),
    path("app_news/", include("app_news.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_files/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "app_files"

urlpatterns = [
    path("", views.main, name="files_page"),
    path("upload/", views.upload_file, name="upload_files"),
    path("image/", views.images, name="image_files"),
    path("video/", views.videos, name="video_files"),
    path("audio/", views.audios, name="audio_files"),
    path("document/", views.docs, name="docs_files"),
    path("archive/", views.archives, name="archives"),
    path("other/", views.other, name="other_files"),

    path("delete-file/<int:f_id>", views.delete_file, name='delete_file'),
    path("edit-description/<int:f_id>", views.edit_description, name='edit_description'),
]

users/urls.py
from django.urls import path, include
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

from . import views
from .forms import LoginForm

app_name = "users"

urlpatterns = [
    path(
        "signup/",
        views.RegisterView.as_view(),
        name="signup",
    ),
    path(
        "signin/",
        LoginView.as_view(template_name="users/signin.html", form_class=LoginForm),
        name="signin",
    ),
    path(
        "signout/",
        LogoutView.as_view(template_name="users/signout.html"),
        name="signout",
    ),
    path("reset-password/", views.ResetPasswordView.as_view(), name="password_reset"),
    path(
        "reset-password/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset-password/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url="/users/reset-password/complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset-password/complete/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

app_files/models.py
from django.db import models
from django.contrib.auth.models import User
from pathlib import Path
from datetime import datetime
import os


CYRILLIC_SYMBOLS = "абвгдеёжзийклмнопрстуфхцчшщъыьэюяєіїґ"
TRANSLATION = (
    "a",
    "b",
    "v",
    "g",
    "d",
    "e",
    "e",
    "j",
    "z",
    "i",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "p",
    "r",
    "s",
    "t",
    "u",
    "f",
    "h",
    "ts",
    "ch",
    "sh",
    "sch",
    "",
    "y",
    "",
    "e",
    "yu",
    "u",
    "ja",
    "je",
    "ji",
    "g",
)

image_files = {".jpeg", ".png", ".jpg", ".svg", ".bmp", ".ico", ".gif"}
video_files = {".mp4", ".mov", ".webm", ".avi", "mkv", ".wmv", ".flv"}
audio_files = {".mp3", ".wav", ".m4a", ".aiff", ".ogg", ".cda"}
document_files = {
    ".docx",
    ".doc",
    ".pptx",
    ".xlsx",
    ".html",
    ".htm",
    ".html5",
    ".txt",
    ".ini",
    ".xml",
    ".ppt",
    ".py",
    ".md",
    ".toml",
    "yml",
    ".cpp",
    ".h",
    ".java",
    ".css",
    ".js",
    ".csv",
}
archive_files = {".rar", ".rar4", ".zip", ".tar", ".bz2", ".7z", ".apk", ".dmg", ".jar"}
other_files = {}


FILE_TYPES = {
    "image": image_files,
    "video": video_files,
    "audio": audio_files,
    "document": document_files,
    "archive": archive_files,
    "other": other_files,
}


def get_file_type(filename):
    """
    Determines the file type of file based on its extension.

    Args:
    filename (str): The name of the file.

    Returns:
    str: The determined file type, or 'other' if the file type cannot be determined.
    """
    extension = Path(filename).suffix
    TRANS = {}
    for cyrillic, latin in zip(CYRILLIC_SYMBOLS, TRANSLATION):
        TRANS[ord(cyrillic)] = latin
        TRANS[ord(cyrillic.lower())] = latin.lower()

    for file_type, extensions in FILE_TYPES.items():
        if extension in extensions:
            return file_type
    return "other"


def update_filename(instance, filename):
    """
    Generates a new filename using the current date and time to ensure uniqueness and sorts it into a folder based on its type.

    Args:
    instance: The instance of the model where the file is being attached.
    filename (str): The original file name uploaded by the user.

    Returns:
    str: A new file path including the folder and new filename.
    """
    filepath = Path(filename)
    now = datetime.now().strftime("%Y%m%d-%H%M")
    filename = f"{now}_{filepath.name}"
    type_id = get_file_type(filepath.name)
    return os.path.join(type_id, filename)


class UserFile(models.Model):
    """
    Model representing a user's file including metadata about the file.

    Attributes:
    filepath (FileField): Path to the file including the filename.
    file_description (CharField): Optional description of the file.
    uploaded_at (DateTimeField): The datetime when the file was uploaded, set automatically.
    user (ForeignKey): Reference to the User who owns the file.
    filename (CharField): The name of the file.
    file_type (CharField): The type of file, determined automatically by the system.
    """

    filepath = models.FileField()
    file_description = models.CharField(max_length=255, null=True)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(
        User, related_name="files", on_delete=models.CASCADE, null=True
    )
    filename = models.CharField(max_length=255, null=True)
    file_type = models.CharField("File type", max_length=50, default="other")

    def save(self, **kwargs):
        """
        Overwrites the save method to ensure the filename and file type are set when the file is saved.
        """
        self.filename = self.filepath.name
        self.file_type = get_file_type(self.filepath.name)
        super().save(**kwargs)

app_files/forms.py
from django.forms import ModelForm, FileField, FileInput, CharField, TextInput
from .models import UserFile


class UploadFileForm(ModelForm):
    filepath = FileField(widget=FileInput(attrs={'class': 'form-control'}))
    file_description = CharField(max_length=255, required=False, widget=TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = UserFile
        fields = ['filepath', 'file_description']
        exclude = ['user']

app_files/views.py
import os

from django.shortcuts import render, redirect
from NeuroContact import settings
from .forms import UploadFileForm
from .models import UserFile
from django.contrib.auth.decorators import login_required


def search_files_by_type(request, file_type: str):
    """
    Searches and returns files filtered by the specified type for the logged-in user.
    If no files are found, returns an empty list.

    Args:
    request: The HTTP request object.
    file_type (str): The type of files to search for.

    Returns:
    list: A list of UserFile instances that match the type.
    """
    try:
        files = UserFile.objects.filter(user=request.user)
        result = files.filter(file_type=file_type)
    except UserFile.DoesNotExist:
        result = []
    return result


@login_required
def main(request):
    """
    Renders the main file page which allows users to navigate to different file categories.

    Args:
    request: The HTTP request object.

    Returns:
    HttpResponse: The rendered main file page.
    """
    return render(request, "app_files/files_page.html", context={'title': 'Download files'})


@login_required
def upload_file(request):
    """
    Handles the uploading of files. If the request method is POST and the form is valid,
    saves the new file associated with the current user and redirects to a specified URL.

    Args:
    request: The HTTP request object.

    Returns:
    HttpResponse: The upload file page, potentially with a form populated with previous input.
    """
    form = UploadFileForm(instance=UserFile())
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES, instance=UserFile())
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.user = request.user
            new_form.save()
            return redirect('app_files:files_page')
    return render(request, 'app_files/upload_files.html', context=
    {
        'title': 'Download files',
        'form': form,
        'media_url': settings.MEDIA_URL
    })


@login_required
def images(request):
    """
    Displays a page with all image files uploaded by the logged-in user.

    Args:
    request: The HTTP request object.

    Returns:
    HttpResponse: The image files page with the list of image files.
    """
    file_type = 'image'
    image_list = search_files_by_type(request, file_type)
    print(image_list)
    return render(request, 'app_files/image_files.html', context=
    {
        'title': 'Download files',
        'image_list': image_list,
        'media_url': settings.MEDIA_URL
    })


@login_required
def videos(request):
    """
    Displays a page with all video files uploaded by the logged-in user.

    Args:
    request: The HTTP request object.

    Returns:
    HttpResponse: The video files page with the list of video files.
    """
    file_type = 'video'
    video_list = search_files_by_type(request, file_type)
    return render(request, 'app_files/video_files.html', context=
    {
        'title': 'Download files',
        'video_list': video_list,
        'media_url': settings.MEDIA_URL
    })


@login_required
def audios(request):
    """
    Displays a page with all audio files uploaded by the logged-in user.

    Args:
    request: The HTTP request object.

    Returns:
    HttpResponse: The audio files page with the list of audio files.
    """
    file_type = 'audio'
    audio_list = search_files_by_type(request, file_type)
    return render(request, 'app_files/audio_files.html', context=
    {
        'title': 'Download files',
        'audio_list': audio_list,
        'media_url': settings.MEDIA_URL
    })


@login_required
def docs(request):
    """
    Displays a page with all document files uploaded by the logged-in user.

    Args:
    request: The HTTP request object.

    Returns:
    HttpResponse: The document files page with the list of document files.
    """
    file_type = 'document'
    document_list = search_files_by_type(request, file_type)
    return render(request, 'app_files/docs_files.html', context=
    {
        'title': 'Download files',
        'document_list': document_list,
        'media_url': settings.MEDIA_URL
    })


@login_required
def archives(request):
    """
    Displays a page with all archive files uploaded by the logged-in user.

    Args:
    request: The HTTP request object.

    Returns:
    HttpResponse: The archives page with the list of archive files.
    """
    file_type = 'archive'
    archive_list = search_files_by_type(request, file_type)
    return render(request, 'app_files/archives.html', context=
    {
        'title': 'Download files',
        'archive_list': archive_list,
        'media_url': settings.MEDIA_URL
    })


@login_required
def other(request):
    """
    Displays a page with all files categorized as 'other' uploaded by the logged-in user.

    Args:
    request: The HTTP request object.

    Returns:
    HttpResponse: The other files page with the list of other files.
    """
    file_type = 'other'
    other_list = search_files_by_type(request, file_type)
    return render(request, 'app_files/other_files.html', context=
    {
        'title': 'Download files',
        'other_list': other_list,
        'media_url': settings.MEDIA_URL
    })


@login_required
def delete_file(request, f_id):
    file = UserFile.objects.filter(pk=f_id, user=request.user)
    try:
        os.unlink(os.path.join(settings.MEDIA_ROOT, str(file.first().filepath)))
    except OSError as e:
        print(e)
    file.delete()
    return redirect(to="app_files:files_page")


@login_required
def edit_description(request, f_id):
    if request.method == "POST":
        file_description = request.POST["file_description"]
        UserFile.objects.filter(pk=f_id, user=request.user).update(file_description=file_description)
        return redirect(to="app_files:files_page")

    file = UserFile.objects.filter(pk=f_id, user=request.user).first()
    ctx = {"title": "CloudyContacts", "file": file, "media": settings.MEDIA_URL}
    return render(request, "app_files/edit_files.html", context=ctx)

app_files/templates/app_files/archives.html
{% extends 'app_main/base.html' %}

{% block files_page %}
{% load static %}

<section class="wrapper style1 fade-up">
    <div class="inner">
        <h2>Your archives</h2>
        <em>Powered by</em>
        <img src="{% static 'app_files/cloudinary.svg' %}" style="width: 20px; height: 20px;"/>

        <div style="display: flex; justify-content: space-between; align-items: center;">
            <a href="{% url 'app_files:upload_files' %}" class="button" style="margin-left: 30px;">
                <i class="fa-solid fa-file-arrow-up" style="margin-left: 8px;"></i>Upload Your File
            </a>
        </div>
        <hr/>

        <div class="table-wrapper" , style="margin-top: 40px">
            <table class="alt">
                <thead>
                <tr>
                    <th>Description</th>
                    <th>Original filename</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
                </thead>
                <tbody>
                {% for f in archive_list %}
                <tr>
                    <td>{{ f.file_description }}</td>
                    <td style="vertical-align: middle; text-align: center;"><a href="{{ f.filepath.url }} " class="button">download</a></td>
                    <td><a href="{% url 'app_files:edit_description' f.id %}" class="button">Edit</a></td>
                    <td><a href="{% url 'app_files:delete_file' f.id %}" class="button">Delete</a></td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="4">No archives available.</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <a href="{% url 'app_files:files_page' %}" class="button" style="margin-right: 30px;">
            <i class="fa fa-angle-double-left" aria-hidden="true"></i> All Files
        </a>

    </div>
</section>

{% endblock %}

app_files/templates/app_files/audio_files.html
{% extends 'app_main/base.html' %}

{% block files_page %}
{% load static %}

<section class="wrapper style1 fade-up">
    <div class="inner">
        <h2>Your audios</h2>
        <em>Powered by</em>
        <img src="{% static 'app_files/cloudinary.svg' %}" style="width: 20px; height: 20px;"/>

        <div style="display: flex; justify-content: space-between; align-items: center;">
            <a href="{% url 'app_files:upload_files' %}" class="button" style="margin-left: 30px;">
                <i class="fa-solid fa-file-arrow-up" style="margin-left: 8px;"></i>Upload Your File
            </a>
        </div>
        <hr/>

        <div class="table-wrapper" , style="margin-top: 40px">
            <table class="alt">
                <thead>
                <tr>
                    <th>Description</th>
                    <th>Original Filename</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
                </thead>
                <tbody>
                {% for f in audio_list %}
                <tr>
                    <td>{{ f.file_description }}</td>
                    <td style="vertical-align: middle; text-align: center;"><a href="{{ f.filepath.url }} " class="button">download</a></td>
                    <td><a href="{% url 'app_files:edit_description' f.id %}" class="button">Edit</a></td>
                    <td><a href="{% url 'app_files:delete_file' f.id %}" class="button">Delete</a></td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="4">No audio files available.</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <a href="{% url 'app_files:files_page' %}" class="button" style="margin-right: 30px;">
            <i class="fa fa-angle-double-left" aria-hidden="true"></i> All Files
        </a>

    </div>
</section>

{% endblock %}

app_files/templates/app_files/docs_files.html
{% extends 'app_main/base.html' %}

{% block files_page %}
{% load static %}

<section class="wrapper style1 fade-up">
    <div class="inner">
        <h2>Your documents</h2>
        <em>Powered by</em>
        <img src="{% static 'app_files/cloudinary.svg' %}" style="width: 20px; height: 20px;"/>

        <div style="display: flex; justify-content: space-between; align-items: center;">
            <a href="{% url 'app_files:upload_files' %}" class="button" style="margin-left: 30px;">
                <i class="fa-solid fa-file-arrow-up" style="margin-left: 8px;"></i>Upload Your File
            </a>
        </div>
        <hr/>

        <div class="table-wrapper" , style="margin-top: 40px">
            <table class="alt">
                <thead>
                <tr>
                    <th>Description</th>
                    <th>Download Link</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
                </thead>
                <tbody>
                {% for f in document_list %}
                <tr>
                    <td>{{ f.file_description }}</td>
                    <td style="vertical-align: middle; text-align: center;"><a href="{{ f.filepath.url }} " class="button">download</a></td>
                    <td><a href="{% url 'app_files:edit_description' f.id %}" class="button">Edit</a></td>
                    <td><a href="{% url 'app_files:delete_file' f.id %}" class="button">Delete</a></td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="4">No documents available.</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <a href="{% url 'app_files:files_page' %}" class="button" style="margin-right: 30px;">
            <i class="fa fa-angle-double-left" aria-hidden="true"></i> All Files
        </a>

    </div>
</section>

{% endblock %}

app_files/templates/app_files/edit_files.html
{% extends 'app_main/base.html' %}

{% block files_page %}
{% load static %}

<section class="wrapper style1 fade-up">
    <div class="inner">
        <h2>Edit File</h2>
        <a href="/app_files" class="button small">to the files page</a>
        <p></p>

        <form method="post">
            {% csrf_token %}
            <div class="fields">
                <div class="field">
                    <label for="file_description">Description:</label>
                    <input type="text" name="file_description" id="file_description" value="{{ file.file_description }}"
                           class="form-control"/>
                </div>
            </div>
            <ul class="actions">
                <li>
                    <button type="submit" class="button primary">Save Changes</button>
                </li>
            </ul>
        </form>

    </div>
</section>

{% endblock %}

app_files/templates/app_files/files_page.html
{% extends 'app_main/base.html' %}

{% block files_page %}
{% load static %}

<section id="files_page" class="wrapper style1 fade-up">
    <div class="inner">
        <h2>Manage Your Files</h2>
        <em>Powered by</em>
            <img src="{% static 'app_files/cloudinary.svg' %}" style="width: 20px; height: 20px;"/>


        <div style="display: flex; justify-content: space-between; align-items: center;">
            <a href="{% url 'app_files:upload_files' %}" class="button" style="margin-left: 30px;">
                <i class="fa-solid fa-file-arrow-up" style="margin-left: 8px;"></i>Upload Your File
            </a>
        </div>
        <hr/>

        <h3>Preview uploaded files:</h3>
        <div class="files-content"
             style="margin: 60px; display: flex; flex-wrap: wrap; justify-content: flex-start; gap: 15px;">
            <button onclick="location.href='{% url 'app_files:image_files' %}'" class="button">
                <i class="fa-solid" style="font-size:36px; color: #8224e3;"></i> Images
            </button>
            <button onclick="location.href='{% url 'app_files:docs_files' %}'" class="button">
                <i class="fa fa-file-text" style="font-size:36px; color: #8224e3;"></i> Documents
            </button>
            <button onclick="location.href='{% url 'app_files:audio_files' %}'" class="button">
                <i class="fa-solid" style="font-size:36px; color: #8224e3;"></i> Audios
            </button>
            <button onclick="location.href='{% url 'app_files:video_files' %}'" class="button">
                <i class="fa-solid" style="font-size:36px; color: #8224e3;"></i> Videos
            </button>
            <button onclick="location.href='{% url 'app_files:archives' %}'" class="button">
                <i class="fa-solid" style="font-size:36px; color: #8224e3;"></i> Archives
            </button>
            <button onclick="location.href='{% url 'app_files:other_files' %}'" class="button">
                <i class="fa-solid" style="font-size:36px; color: #8224e3;"></i> Others
            </button>
        </div>

    </div>
</section>
<style>
    .button {
        display: flex;
        align-items: center;
    }

    .button i {
        margin-right: 10px;
        margin-top: 10px;
    }

    .button:hover {
        background-color: #6f1fa1;
    }
</style>

{% endblock %}

app_files/templates/app_files/image_files.html
{% extends 'app_main/base.html' %}

{% block files_page %}
{% load static %}

<section class="wrapper style1 fade-up">
    <div class="inner">
        <h2>Your images</h2>
        <em>Powered by</em>
        <img src="{% static 'app_files/cloudinary.svg' %}" style="width: 20px; height: 20px;"/>

        <div style="display: flex; justify-content: space-between; align-items: center;">
            <a href="{% url 'app_files:upload_files' %}" class="button" style="margin-left: 30px;">
                <i class="fa-solid fa-file-arrow-up" style="margin-left: 8px;"></i>Upload Your File
            </a>
        </div>
        <hr/>


        <div class="table-wrapper" , style="margin-top: 40px">
            <table class="alt">
                <thead>
                <tr>
                    <th>Preview</th>
                    <th>Description</th>
                    <th>Download Link</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
                </thead>
                <tbody>
                {% for f in image_list %}
                <tr>
                        <td style="width: 15%; text-align: center; vertical-align: middle;"><img style="max-width: 100%; max-height: 100%;display: inline-block;" src="{{ f.filepath.url }} "/></td>
                        <td style="vertical-align: middle; ">{{ f.file_description }}</td>
                        <td style="vertical-align: middle; text-align: center;"><a href="{{ f.filepath.url }}">download</a></td>
                        <td style="vertical-align: middle; text-align: center;"><a href="{% url 'app_files:edit_description' f.id %}" class="button">Edit</a></td>
                        <td style="vertical-align: middle; text-align: center;"><a href="{% url 'app_files:delete_file' f.id %}" class="button">Delete</a></td>
                    </tr>
                {% empty %}
                <tr>
                    <td colspan="4">No images available.</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <a href="{% url 'app_files:files_page' %}" class="button" style="margin-right: 30px;">
            <i class="fa fa-angle-double-left" aria-hidden="true"></i> All Files
        </a>

    </div>
</section>

{% endblock %}

app_files/templates/app_files/other_files.html
{% extends 'app_main/base.html' %}

{% block files_page %}
{% load static %}

<section class="wrapper style1 fade-up">
    <div class="inner">
        <h2>Your other files</h2>
        <em>Powered by</em>
        <img src="{% static 'app_files/cloudinary.svg' %}" style="width: 20px; height: 20px;"/>

        <div style="display: flex; justify-content: space-between; align-items: center;">
            <a href="{% url 'app_files:upload_files' %}" class="button" style="margin-left: 30px;">
                <i class="fa-solid fa-file-arrow-up" style="margin-left: 8px;"></i>Upload Your File
            </a>
        </div>
        <hr/>

        <div class="table-wrapper" , style="margin-top: 40px">
            <table class="alt">
                <thead>
                <tr>
                    <th>Description</th>
                    <th>Download Link</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
                </thead>
                <tbody>
                {% for f in other_list %}
                <tr>
                    <td>{{ f.description }}</td>
                    <td style="vertical-align: middle; text-align: center;"><a href="{{ f.filepath.url }} " class="button">download</a></td>
                    <td><a href="{% url 'app_files:edit_description' f.id %}" class="button">Edit</a></td>
                    <td><a href="{% url 'app_files:delete_file' f.id %}" class="button">Delete</a></td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="4">No other files available.</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <a href="{% url 'app_files:files_page' %}" class="button" style="margin-right: 30px;">
            <i class="fa fa-angle-double-left" aria-hidden="true"></i> All Files
        </a>

    </div>
</section>

{% endblock %}

app_files/templates/app_files/upload_files.html
{% extends 'app_main/base.html' %}

{% block files_page %}
{% load static %}

<section class="wrapper style1 fade-up">
    <div class="inner">
        <h2>Upload File</h2>

        <a href="/app_files" class="button small">to the files page</a>
        <p></p>

        <form action="{% url 'app_files:upload_files' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="fields">
                <div class="field half">
                    <label class="form-label">Description</label>
                    {{ form.file_description }}
                </div>
            </div>
            <div class="field half">
                <label class="button">
                    Choose a file
                    <input type="file" name="filepath" style="display: none;">
                </label>
                <!--<label class="form-label">File</label>
                {{ form.filepath }}-->
            </div>
            <ul class="actions">
                <li>
                    <button class="button submit">Upload</button>
                </li>
            </ul>
        </form>

    </div>
</section>

{% endblock %}

app_files/templates/app_files/video_files.html
{% extends 'app_main/base.html' %}

{% block files_page %}
{% load static %}

<section class="wrapper style1 fade-up">
    <div class="inner">
        <h2>Your videos</h2>
        <em>Powered by</em>
        <img src="{% static 'app_files/cloudinary.svg' %}" style="width: 20px; height: 20px;"/>

        <div style="display: flex; justify-content: space-between; align-items: center;">
            <a href="{% url 'app_files:upload_files' %}" class="button" style="margin-left: 30px;">
                <i class="fa-solid fa-file-arrow-up" style="margin-left: 8px;"></i>Upload Your File
            </a>
        </div>
        <hr/>

        <div class="table-wrapper" , style="margin-top: 40px">
            <table class="alt">
                <thead>
                <tr>
                    <th>Description</th>
                    <th>Original Filename</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
                </thead>
                <tbody>
                {% for f in video_list %}
                <tr>
                    <td>{{ f.file_description }}</td>
                    <td style="vertical-align: middle; text-align: center;"><a href="{{ f.filepath.url }} " class="button">download</a></td>
                    <td><a href="{% url 'app_files:edit_description' f.id %}" class="button">Edit</a></td>
                    <td><a href="{% url 'app_files:delete_file' f.id %}" class="button">Delete</a></td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="4">No videos available.</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <a href="{% url 'app_files:files_page' %}" class="button" style="margin-right: 30px;">
            <i class="fa fa-angle-double-left" aria-hidden="true"></i> All Files
        </a>

    </div>
</section>

{% endblock %}